disk done but order bug

diff --git a/airootfs/usr/bin/formatscript b/airootfs/usr/bin/formatscript
--- a/airootfs/usr/bin/formatscript
+++ b/airootfs/usr/bin/formatscript
@@ -1,15 +1,24 @@
 #!/usr/bin/env bash
 
+source ./partitionscript
+
 # Define partition paths (Adjust if using NVMe)
 echo "Defining partition paths..."
-BOOT_PART="${DISK}/dev/sda1"
-SWAP_PART="${DISK}/dev/sda2"
-ROOT_PART="${DISK}/dev/sda3"
+BOOT_PART="${DISK}/dev/sda1" || { echo "Failed to define boot partition"; exit 1; } 
+ROOT_PART="${DISK}/dev/sda3" || { echo "Failed to define root partition"; exit 1; } 
+
+if [ "$swapyn" == "y" ]; then
+    SWAP_PART="${DISK}/dev/sda2" || { echo "Failed to define swap partition"; exit 1; } 
+
 echo "Success."
 
 # Format partitions
+
+if [ "$swapyn" == "y" ]; then
+    mkswap "$SWAP_PART" || { echo "Failed to format swap partition"; exit 1; } 
+fi
+
 echo "Formating partitions..."
-mkfs.fat -F 32 "$BOOT_PART"
-mkfs.ext4 -F "$ROOT_PART"
-mkswap "$SWAP_PART"
+mkfs.fat -F 32 "$BOOT_PART"  || { echo "Failed to format boot partition"; exit 1; } 
+mkfs.ext4 -F "$ROOT_PART"  || { echo "Failed to format root partition"; exit 1; } 
 echo "Success."
diff --git a/airootfs/usr/bin/mountingscript b/airootfs/usr/bin/mountingscript
--- a/airootfs/usr/bin/mountingscript
+++ b/airootfs/usr/bin/mountingscript
@@ -1,7 +1,13 @@
 #!/usr/bin/env bash
 
-BOOT_PART="${DISK}/dev/sda1"
-SWAP_PART="${DISK}/dev/sda2"
+source ./partitionscript
+
+BOOT_PART="${DISK}/dev/sda1" 
+
+if [ "$swapyn" == "y" ]; then
+    mkswap "$SWAP_PART" || { echo "Failed to format swap partition"; exit 1; } 
+fi
+
 ROOT_PART="${DISK}/dev/sda3"
 
 # Mount Root
diff --git a/airootfs/usr/bin/partitionscript b/airootfs/usr/bin/partitionscript
--- a/airootfs/usr/bin/partitionscript
+++ b/airootfs/usr/bin/partitionscript
@@ -2,27 +2,52 @@
 
 # Define the target drive
 echo "Defining target device..."
-DISK="/dev/sda"
+DISK="/dev/sda" || { echo "Faild to find disk."; exit 1; }
 echo "Success."
 
 # 1. Create a new GPT partition table
 echo "Creating partition table..."
-parted -s "$DISK" mklabel gpt
+parted -s "$DISK" mklabel gpt || { echo "Faild to create partition table"; exit 1; }
 echo "Success."
 
 # 2. Create UEFI Boot Partition (1GiB)
 echo "Creating UEFI Boot Partition (1GiB)..."
-parted -s "$DISK" mkpart primary fat32 1MiB 1025MiB
-parted -s "$DISK" set 1 esp on
+parted -s "$DISK" mkpart primary fat32 1MiB 1025MiB || { echo "Faild to create UEFI boot partition."; exit 1; }
+parted -s "$DISK" set 1 esp on || { echo "Faild to create UEFI boot partition."; exit 1; }
 echo "Success."
 
-# 3. Create Swap Partition (4GB)
-echo "Creating Swap Partition (4GB)..."
-parted -s "$DISK" mkpart primary linux-swap 1025MiB 5121MiB
-echo "Success."
+swapstart=1025
 
-# 4. Create Root Partition (Remaining space)
-echo "Using the remaining space for root partiton.."
-parted -s "$DISK" mkpart primary ext4 5121MiB 100%
+# 3. Create Swap Partition
+read -p "Create swap partition? Y/n? " swapyn
+swapyn=${swapyn:-"y"}
+
+if [ "$swapyn" == "y" ]; then
+    while [ -z "$swapsize" ]; do
+        read -p "Define size of swap partition. (In MiB, Minimum 1000) " swapsize
+    done
+
+    echo "Creating Swap Partition ($swapsize)..."
+    parted -s "$DISK" mkpart primary linux-swap "${swapstart}MiB" "$((swapstart + swapsize))MiB"
+    echo "Success."
+fi
+
+# calc start end root
+rootstart=$((swapstart + ${swapsize:-0}))
+
+# 4. root
+read -p "Define size of root partition. (In MiB, 10000 if empty, 10000 minimum) " rootsize
+rootsize=${rootsize:-10000}
+
+while [ "$rootsize" -lt 10000 ]; do
+    echo "Error: $rootsize is too small. Minimum is 10000."
+    read -p "Define size of root partition: " rootsize
+    rootsize=${rootsize:-10000}
+done
+
+
+echo "Creating root partition ($rootsize)..."
+parted -s "$DISK" mkpart primary ext4 "${rootstart}MiB" "$((rootstart + rootsize))MiB"
+
 echo "Success."
 echo "Successfully created UEFI, swap and root partition."
