path bug format

diff --git a/airootfs/usr/bin/formatscript b/airootfs/usr/bin/formatscript
--- a/airootfs/usr/bin/formatscript
+++ b/airootfs/usr/bin/formatscript
@@ -5,10 +5,10 @@ source ./partitionscript
 # Define partition paths (Adjust if using NVMe)
 echo "Defining partition paths..."
 BOOT_PART="${DISK}/dev/sda1" || { echo "Failed to define boot partition"; exit 1; } 
-ROOT_PART="${DISK}/dev/sda3" || { echo "Failed to define root partition"; exit 1; } 
+ROOT_PART="${DISK}/dev/sda2" || { echo "Failed to define root partition"; exit 1; } 
 
 if [ "$swapyn" == "y" ]; then
-    SWAP_PART="${DISK}/dev/sda2" || { echo "Failed to define swap partition"; exit 1; } 
+    SWAP_PART="${DISK}/dev/sda3" || { echo "Failed to define swap partition"; exit 1; } 
 
 echo "Success."
 
diff --git a/airootfs/usr/bin/mountingscript b/airootfs/usr/bin/mountingscript
--- a/airootfs/usr/bin/mountingscript
+++ b/airootfs/usr/bin/mountingscript
@@ -5,10 +5,10 @@ source ./partitionscript
 BOOT_PART="${DISK}/dev/sda1" 
 
 if [ "$swapyn" == "y" ]; then
-    mkswap "$SWAP_PART" || { echo "Failed to format swap partition"; exit 1; } 
+    SWAP_PART="${DISK}/dev/sda3" || { echo "Failed to format swap partition"; exit 1; } 
 fi
 
-ROOT_PART="${DISK}/dev/sda3"
+ROOT_PART="${DISK}/dev/sda2"
 
 # Mount Root
 echo "Mounting root..."
@@ -22,8 +22,11 @@ mount "$BOOT_PART" /mnt/boot
 echo "Success."
 
 # Enable Swap
-echo "Enabling swap..."
-swapon "$SWAP_PART"
-echo "Success."
+if [ "$swapyn" == "y" ]; then
+    echo "Enabling swap..."
+    swapon "$SWAP_PART"
+    echo "Success."
+fi
+
 
 echo "Disk $DISK has been partitioned, formatted, and mounted to /mnt."
