partition NVMe fix

diff --git a/airootfs/usr/bin/formatscript b/airootfs/usr/bin/formatscript
--- a/airootfs/usr/bin/formatscript
+++ b/airootfs/usr/bin/formatscript
@@ -1,16 +1,28 @@
 #!/usr/bin/env bash
 
-source ./partitionscript
+ENV_FILE="/tmp/partition.env"
+if [ ! -f "$ENV_FILE" ]; then
+    echo "Missing $ENV_FILE. Run partitionscript first."
+    exit 1
+fi
+source "$ENV_FILE"
 
-# Define partition paths (Adjust if using NVMe)
 echo "Defining partition paths..."
-BOOT_PART="${DISK}/dev/sda1" || { echo "Failed to define boot partition"; exit 1; } 
-ROOT_PART="${DISK}/dev/sda2" || { echo "Failed to define root partition"; exit 1; } 
+
+# check if disk ends with digitt
+if [[ $DISK =~ [0-9]$ ]]; then
+    PART_SEP="p"
+else
+    PART_SEP=""
+fi
+
+BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
+ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
 
 if [ "$swapyn" == "y" ]; then
-    SWAP_PART="${DISK}/dev/sda3" || { echo "Failed to define swap partition"; exit 1; } 
-
-echo "Success."
+    SWAP_PART="${DISK}${PART_SEP}3" || { echo "Failed to define swap partition"; exit 1; } 
+    echo "Success."
+fi
 
 # Format partitions
 
diff --git a/airootfs/usr/bin/mountingscript b/airootfs/usr/bin/mountingscript
--- a/airootfs/usr/bin/mountingscript
+++ b/airootfs/usr/bin/mountingscript
@@ -1,14 +1,29 @@
 #!/usr/bin/env bash
 
-source ./partitionscript
+ENV_FILE="/tmp/partition.env"
+if [ ! -f "$ENV_FILE" ]; then
+    echo "Missing $ENV_FILE. Run partitionscript first."
+    exit 1
+fi
+source "$ENV_FILE"
 
-BOOT_PART="${DISK}/dev/sda1" 
 
-if [ "$swapyn" == "y" ]; then
-    SWAP_PART="${DISK}/dev/sda3" || { echo "Failed to format swap partition"; exit 1; } 
+echo "Defining partition paths..."
+
+# check last disk digit
+if [[ $DISK =~ [0-9]$ ]]; then
+    PART_SEP="p"
+else
+    PART_SEP=""
 fi
 
-ROOT_PART="${DISK}/dev/sda2"
+BOOT_PART="${DISK}${PART_SEP}1" || { echo "Failed to define boot partition"; exit 1; } 
+ROOT_PART="${DISK}${PART_SEP}2" || { echo "Failed to define root partition"; exit 1; } 
+
+if [ "$swapyn" == "y" ]; then
+    SWAP_PART="${DISK}${PART_SEP}3" || { echo "Failed to define swap partition"; exit 1; } 
+    echo "Success."
+fi
 
 # Mount Root
 echo "Mounting root..."
diff --git a/airootfs/usr/bin/partitionscript b/airootfs/usr/bin/partitionscript
--- a/airootfs/usr/bin/partitionscript
+++ b/airootfs/usr/bin/partitionscript
@@ -1,7 +1,15 @@
 #!/usr/bin/env bash
 
 echo "Defining target device..."
-DISK="/dev/sda" || { echo "Faild to find disk."; exit 1; }
+
+# List disks and prompt
+echo "Available disks: (if empty run lsblk)"
+
+lsblk -dn -o NAME,SIZE,MODEL,TYPE | awk '$4=="disk"{print $1, $2, $3}' 
+
+
+read -p "Enter disk (e.g. sda, nvme0n1): " diskname
+DISK="/dev/$diskname"|| { echo "Faild to find disk."; exit 1; }
 echo "Success."
 
 echo "Creating partition table..."
@@ -47,3 +55,11 @@ echo "Successfully created UEFI, root and swap partition."
 export swapyn
 export swapsize
 export rootsize
+
+ENV_FILE="/tmp/partition.env"
+cat > "$ENV_FILE" <<EOF
+export DISK="$DISK"
+export rootsize="$rootsize"
+export swapsize="$swapsize"
+export swapyn="$swapyn"
+EOF
